SOS_LIBNAME=lib/libsos.a
SOS_LIBOBJS=\
	sos/sos_prot.o \
	sos/asg_ctx.o \
	sos/asg_rdma.o \
	sos/asg_serdes.o \
	sos/asg_ignore.o \
	sos/asg_request.o \
	sos/asg_poll.o \
	sos/asg_misc1.o \
	sos/asg_create_transport.o \
	sos/asg_create_location.o \
	sos/asg_initialize.o \
	sos/asg_batch.o \
	sos/asg_write.o \
	sos/asg_read.o
SOS_TESTS=\
	sos/testit \
	sos/randtest
