SERVER_AENAMES= \
	asg_exec.o		\
	cb_proxy.o		\
	signal_shutdown.o

SERVER_AEOBJS=$(patsubst %.o,server/%.o,$(SERVER_AENAMES))

SERVER_CNAMES= \
	sos_prot.o		\
	xm_singleton.o		\
	xmu_addr.o		\
	xmu_buf_pool.o


SERVER_COBJS=$(patsubst %.o,server/%.o,$(SERVER_CNAMES))

SERVER_OBJS=$(SERVER_COBJS) $(SERVER_AEOBJS)

SERVER_SERVER=server/server
